name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ton06/workflows/.github/workflows/deploy.yml@main
    with:
      aws-region: "sa-east-1"
      environment: "dev"